/* Automatically generated by po2tbl.sed from gtkfaucet.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"(c) Twisted Matrix Enterprises 1999", 2},
  {"This is the GNOME-ized version of the Twisted Reality project.", 3},
  {"Reality Faucet", 4},
  {"NameLabel", 5},
  {"Description Not Updated!", 6},
  {"ItemList Not Updated!", 7},
  {"Reality Faucet 1.1.2 Protocol V3", 8},
  {"Reality Login", 9},
  {"\
GTK Faucet 1.1.2\n\
Protocol V3", 10},
  {"Character Name:", 11},
  {"Password:", 12},
  {"Hostname:", 13},
  {"reality.divunal.com", 14},
  {"Reality Message", 15},
  {"This is a generic error message.", 16},
  {"Unnamed Response Window", 17},
  {"Couldn't find pixmap file: %s", 18},
  {"Couldn't create pixmap from file: %s", 19},
};

int _msg_tbl_length = 19;
