
version="0.3"

disclaimer="""
THIS IS ALPHA QUALITY SOFTWARE AND SHOULD NOT BE USED FOR ANY PURPOSES
EXCEPT THE PURPOSES YOU WOULD USE ALPHA SOFTWARE FOR.  I WOULD SAY
SOMETHING ELSE MEANINGFUL HERE ABOUT THE LACK OF A WARRANTY BUT I'M
TOO EXCITED ABOUT TYPING IN ALL CAPITAL LETTERS.

OH YEAH, THERE IS NO WARRANTY, EITHER EXPRESSED OR IMPLIED, INCLUDING
BUT NOT LIMITED TO THE IMPLIED WARRANTY OF MERCHANTIBILITY.  NOBODY
SOLD THIS TO YOU, OR RATHER, THEY CERTAINLY SHOULDN'T HAVE (IT'S NOT
MERCHANTIBLE, DUH), SO I CAN'T THINK WHY THAT WARRANTY IS IMPLIED.
""" 

copyright="(c) 2000 Twisted Matrix Enterprises, all rights reserved."

longversion="Twisted Reality II %s"% version
