/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_aboutbox (void);
GtkWidget* create_gamewindow (void);
GtkWidget* create_loginwindow (void);
GtkWidget* create_answerdialog (void);
GtkWidget* create_responsewindow (void);
