/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "history.h"
#include "fileutils.h"
#include "interface.h"
#include "callbacks.h"
#include "support.h"
#include "faucet.h"

int
main (int argc, char *argv[])
{
  g_set_prgname(argv[0]);
  if(strchr(argv[0],'/'))
	{
	  cd(g_dirname(argv[0]));
	}
  faucet_init();
  history_init();

  
  bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
  textdomain (PACKAGE);

  gnome_init ("gtkfaucet", VERSION, argc, argv);
  loginwindow=create_loginwindow();
  gamewindow=create_gamewindow();
  gtk_widget_show(loginwindow);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

  gtk_main ();
  return 0;
}

