# Copy this file to a file called "Makefile.config.local" first, to avoid
# conflicts with CVS updates.

# The root of your Java package heirarchy

JAVA_HOME=/opt/java

# The location and options to your Java compiler

JAVAC=/usr/bin/jikes +E +P

#JAVAC=$(JAVA_HOME)/bin/javac

# This keeps the compile nice and quiet.  Comment out this line if you want
# impressive looking make-debugging stuff.

# MAKEFLAGS="-s"

# Binary directory, where binaries should go.

BINDIR=$(CURDIR)/../javaclasses

SCRIPTDIR=$(CURDIR)/../scripts

# Jars directory, where the vendor-provided jarfiles that you're working with
# should go.

JARDIR=$(CURDIR)/../jars

# The actual jarfiles that are included

JARS=$(JARDIR)/swing.jar:$(JARDIR)/images.jar:$(JARDIR)/mrjstubs.jar

# Location of the system's classes.zip

CLASSZIP=$(JAVA_HOME)/lib/classes.zip

# Location of the system's RMIC compiler (remote method invocation)

RMIC=$(JAVA_HOME)/bin/rmic

# Complete classpath to be used in runscripts, etcetera.

CLASSPATH=$(CLASSZIP):$(JARS):$(BINDIR):$(JARDIR):.

# Full compile-command, built mostly out of the pieces you see above.

COMPILE=$(JAVAC) -classpath $(CLASSPATH) -d $(BINDIR)
